BULK INSERT dbo.MyCalendar FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/MyCalendar.2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.Class FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Class.2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.Grade FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Grade.2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.Student FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Student.2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.Exam FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Exam.2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.SubjectKlassRel FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/SubjectKlassRel.2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.Teacher FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Teacher.2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')