BULK INSERT dbo.Class FROM '/Users/admin1/GoogleDrive/ProjectsJava/db-generator/bulks/Class2016.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.Grade FROM '/Users/admin1/GoogleDrive/ProjectsJava/db-generator/bulks/Grade2016.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.Student FROM '/Users/admin1/GoogleDrive/ProjectsJava/db-generator/bulks/Student2016.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.Exam FROM '/Users/admin1/GoogleDrive/ProjectsJava/db-generator/bulks/Exam2016.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.Examination FROM '/Users/admin1/GoogleDrive/ProjectsJava/db-generator/bulks/Examination2016.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.SubjectKlassRel FROM '/Users/admin1/GoogleDrive/ProjectsJava/db-generator/bulks/SubjectKlassRel2016.bulk' WITH (FIELDTERMINATOR=';')
