BULK INSERT dbo.Class FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Class2017.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.Grade FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Grade2017.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.Student FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Student2017.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.Exam FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Exam2017.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.SubjectKlassRel FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/SubjectKlassRel2017.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')