BULK INSERT dbo.Class FROM '/home/bulks/Class2015.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.Grade FROM '/home/bulks/Grade2015.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.Student FROM '/home/bulks/Student2015.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.Exam FROM '/home/bulks/Exam2015.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.Examination FROM '/home/bulks/Examination2015.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.SubjectKlassRel FROM '/home/bulks/SubjectKlassRel2015.bulk' WITH (FIELDTERMINATOR=';')
