BULK INSERT dbo.Class FROM '/home/bulks/Class2016.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.Grade FROM '/home/bulks/Grade2016.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.Student FROM '/home/bulks/Student2016.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.Exam FROM '/home/bulks/Exam2016.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.Examination FROM '/home/bulks/Examination2016.bulk' WITH (FIELDTERMINATOR=';')
BULK INSERT dbo.SubjectKlassRel FROM '/home/bulks/SubjectKlassRel2016.bulk' WITH (FIELDTERMINATOR=';')
