BULK INSERT dbo.Class FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Class2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.Grade FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Grade2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.Student FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Student2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.Exam FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Exam2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.Examination FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/Examination2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')
BULK INSERT dbo.SubjectKlassRel FROM '/Users/admin1/GoogleDrive/JavaProjects/db-generator/bulks/SubjectKlassRel2015.bulk' WITH (FIELDTERMINATOR=';', ROWTERMINATOR='|')