/*
DROP TABLE IF EXISTS SubjectKlassRel
DROP TABLE IF EXISTS SubjectTeacherRel
DROP TABLE IF EXISTS Examination
DROP TABLE IF EXISTS Subject
DROP TABLE IF EXISTS Class
DROP TABLE IF EXISTS Teacher
DROP TABLE IF EXISTS Grade
DROP TABLE IF EXISTS Student
DROP TABLE IF EXISTS Exam
*/
CREATE TABLE Subject
(
    ID INTEGER IDENTITY(1, 1) PRIMARY KEY,
    Name nvarchar(40) NOT NULL,
)
CREATE TABLE Teacher
(
    Name nvarchar(40) NOT NULL,
    PESEL nvarchar(11) PRIMARY KEY,
    Surname nvarchar(40) NOT NULL,
    Title nvarchar(40) NOT NULL,
)
CREATE TABLE Class
(
    ID INTEGER IDENTITY(1, 1) PRIMARY KEY,
    Sign nvarchar(1) NOT NULL,
    Tutor_PESEL nvarchar(11) NOT NULL FOREIGN KEY REFERENCES Teacher,
    OriginYear INTEGER NOT NULL,
)
CREATE TABLE Student
(
    Name nvarchar(40) NOT NULL,
    PESEL nvarchar(11) PRIMARY KEY,
    Surname nvarchar(40) NOT NULL,
    Class_ID INTEGER NOT NULL FOREIGN KEY REFERENCES Class
)
CREATE TABLE Grade
(
    ID INTEGER IDENTITY(1, 1) PRIMARY KEY,
    Year INTEGER NOT NULL,
    Grade FLOAT NOT NULL,
    Subject_ID INTEGER NOT NULL FOREIGN KEY REFERENCES Subject,
    Teacher_PESEL nvarchar(11) NOT NULL FOREIGN KEY REFERENCES Teacher,
    Student_PESEL nvarchar(11) NOT NULL FOREIGN KEY REFERENCES Student,
)
CREATE TABLE Exam
(
    ID INTEGER IDENTITY(1, 1) PRIMARY KEY,
    Name nvarchar(40) NOT NULL,
    Year INTEGER NOT NULL,
)
CREATE TABLE Examination
(
    ID INTEGER IDENTITY(1, 1) PRIMARY KEY,
    Year INTEGER NOT NULL,
    Result FLOAT NOT NULL,
    Student_PESEL nvarchar(11) NOT NULL FOREIGN KEY REFERENCES Student,
    Exam_ID INTEGER NOT NULL FOREIGN KEY REFERENCES Exam
)
CREATE TABLE SubjectTeacherRel
(
    ID INTEGER IDENTITY(1, 1) PRIMARY KEY,
    Subject_ID INTEGER NOT NULL FOREIGN KEY REFERENCES Subject,
    Teacher_PESEL nvarchar(11) NOT NULL FOREIGN KEY REFERENCES Teacher,
)
CREATE TABLE SubjectKlassRel
(
    ID INTEGER IDENTITY(1, 1) PRIMARY KEY,
    Subject_ID INTEGER NOT NULL FOREIGN KEY REFERENCES Subject,
    Class_ID INTEGER NOT NULL FOREIGN KEY REFERENCES Class,
    Teacher_PESEL nvarchar(11) NOT NULL FOREIGN KEY REFERENCES Teacher,
)
