UPDATE dbo.Student SET Surname = 'Walczak' WHERE ID = '158'
UPDATE dbo.Student SET Surname = 'Pawlak' WHERE ID = '449'
UPDATE dbo.Student SET Surname = 'Jabłońska' WHERE ID = '355'
UPDATE dbo.Student SET Surname = 'Pawłowska' WHERE ID = '283'
UPDATE dbo.Student SET Surname = 'Woźniak' WHERE ID = '561'